project: "intellilung-rl"
name: "EDAC"
job_type: "rl_train"
steps: 400_000
eval_every: 10_000
log_every: 100
checkpoint_every: 50_000
#save_only_last_checkpoint: True
root_path: logs

batch_size: 256
gamma: 0.99


device: cuda


actor_learning_rate: 0.0003
alpha_learning_rate: 0.0003

buffer_size: 1_000_000
critic_learning_rate: 0.0003
deterministic_torch: false
eta: 10.0
eval_seed: 42
hidden_dims: [256, 256, 256]
max_action: 1.0

num_critics: 30
tau: 0.005



