project: "intellilung-rl"
job_type: "rl_eval"
name: "Dist-Ensemble-fqe"
steps: 50_000
eval_every: 1000
log_every: 100
checkpoint_every: 20_000
discount: 0.99
lr: !!float 1e-4
hidden_dims: [256, 256, 256]
batch_size: 1280
tau: !!float 5e-3
save_only_last_checkpoint: True
weight_decay: !!float 1e-5
num_critics: 5
n_atoms: 20