combined_mimic_eicu_hirid:
  action_space:
    - vent_vt_action
    - vent_rrtot
    - vent_peep
    - vent_fio2
    - vent_pinsp-peep
    - vent_mode
  action_type: discrete
  episode_id_column: episode_id
  historized_actions: false
  history_len: 0
  patient_alive_col: daemo_discharge

  state_vector_columns:
    - drugs_vaso4h
    - vent_pinsp
    - blood_chlorid
    - vital_hr
    - blood_wbc
    - blood_pao2
    - vital_SBP
    - blood_be
    - blood_paco2
    - vital_map
    - vital_DBP
    - blood_potas
    - blood_INR
    - blood_ph
    - daemo_weight
    - state_ivfluid4h
    - state_urin4h
    - blood_sao2
    - daemo_height
    - daemo_age
    - blood_hb
    - blood_sodium
    - blood_hco3
    - daemo_sex
    - vital_spo2
    - vent_vt_obs